# Site settings
title: SNU Dentistry
email: dentistry@snu.ac.kr
description: > # this means to ignore newlines until "baseurl:"
  Seoul National University School of Dentistry;
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  snudentistry
